spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          password: 3164a25789b0p228
          username: sucaiji
          uri: https://github.com/sucaiji/SrpingcloudConfig
          search-paths: respo
      label: master
server:
  port: 8899
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
